### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by bkamantha** [nrsyed/computer-vision#4]
$ python3 get_video_pixel.py 

select timeout
VIDIOC_DQBUF: Resource temporarily unavailable
Traceback (most recent call last):
  File "get_video_pixel.py", line 20, in <module>
    snapshot = np.zeros(frame.shape, dtype=np.uint8)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by nrsyed** [comment]
May be a problem with your opencv installation? See if this helps:
https://stackoverflow.com/questions/54538823/opencv-cannot-find-webcam-but-cheese-can

**Comment by bkamantha** [comment]
This error occurred because i hve another camera driver install on my system,at that time its not connected into pc
